name: Deploy Schema Change

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
	  packages:
            - snowflake-connector-python
            - name: Install schemachange
              run: pip install schemachange

            - name: Run schemachange
	env:
          SF_ACCOUNT: ${{secrets.SF_ACCOUNT}}
          SF_USERNAME: ${{secrets.SF_USERNAME}}
          SF_ROLE: ${{secrets.SF_ROLE}}
          SF_WAREHOUSE: ${{secrets.SF_WAREHOUSE}}
          SF_DATABASE: ${{secrets.SF_DATABASE}}
          SF_PASSWORD: ${{secrets.SF_PASSWORD}}
          run: | 
         
           echo "SNOWFLAKE_ENV=dev" >> $GITHUB_ENV
           if [[ $GITHUB_REF == refs/heads/main ]]; then
	   echo "Deploying to production..."

	   echo "Skipping production deployment..."
            
           fi 
           - name: Deploy to Snowflake
            run: |
           if [[ $SNOWFLAKE_ENV == "dev" ]]; then
            schemachange -f ./schema_changes -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.DEV.METADATA.CHANGE_HISTORY --create-change-history-table
           elif [[ $SNOWFLAKE_ENV == "prod" ]]; then
            schemachange -f ./schema_changes -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.PROD.METADATA.CHANGE_HISTORY --create-change-history-table
            fi
